name: AutoMessage
version: @version@-@apiversion@
description: AutoMessage
authors: [ DartPower, Shawshark ]
website: https://github.com/dptmc/AutoMessage
main: io.dpteam.AutoMessage.Main

commands:
  automessage: